const RoomsActionTypes = {
    FILTER_ROOM_TYPES: 'FILTER_ROOM_TYPES',
    FILTER_ROOM_CAPACITY: 'FILTER_ROOM_CAPACITY',
    FILTER_PRICE_RANGE: 'FILTER_PRICE_RANGE',
    FILTER_MIN_SIZE: 'FILTER_MIN_SIZE',
    FILTER_MAX_SIZE: 'FILTER_MAX_SIZE',
    FILTER_BREAFAST: 'FILTER_BREAKFAST',
    FILTER_PETS: 'FILTER_PETS'
};

export default RoomsActionTypes;