const RoomsActionTypes = {
    FILTER_ROOM_TYPES: 'FILTER_ROOM_TYPES',
    FILTER_ROOM_CAPACITY: 'FILTER_ROOM_CAPACITY',
    FILTER_PRICE_RANGE: 'FILTER_PRICE_RANGE',
    FILTER_BREAFAST_PETS: 'FILTER_BREAKFAST_PETS'
};

export default RoomsActionTypes;